# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-10 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=30, verbose_name='Tytu\u0142')),
                ('przedmiot', models.TextField(blank=True, help_text='Przedmiot')),
                ('autor', models.TextField(blank=True, help_text='Autor')),
                ('wydawnictwo', models.TextField(blank=True, help_text='Wydawnictwo')),
                ('kontakt', models.TextField(blank=True, help_text='Kontakt')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=5)),
                ('opis', models.TextField(blank=True, help_text='Opis Ksiazki')),
                ('data', models.DateField(auto_now_add=True, verbose_name='dodano')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ksiazki',
            },
        ),
    ]
