# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazki',
            name='stan',
            field=models.CharField(choices=[('U', 'U\u017cywana'), ('N', 'Nowa')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='autor',
            field=models.CharField(max_length=30, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='kontakt',
            field=models.CharField(max_length=30, verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='opis',
            field=models.CharField(max_length=30, verbose_name='Opis Ksiazki'),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='przedmiot',
            field=models.CharField(max_length=30, verbose_name='Przedmiot'),
        ),
        migrations.AlterField(
            model_name='ksiazki',
            name='wydawnictwo',
            field=models.CharField(max_length=30, verbose_name='Wydawnictwo'),
        ),
    ]
